remote_theme: jekyll/minima@bf9ef98
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
  hide_site_feed_link: true
  nav_pages:
    - game_rules/game_rules.md
    - index.md
  social_links:
    - title: Three corners on GitHub
      icon: github
      url: "https://github.com/orange223171/three-corners"
